[profile.release]
debug = true
incremental = true
lto = "off"


[workspace]
members = [
    "crates/*",
]
resolver = "2"

[workspace.dependencies]
motus = { path = "crates/motus" }
cli = { path = "crates/motus-cli" }
wasm = { path = "crates/motus-wasm" }